name: Unit

on:
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    name: Unit Tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 12.x
          - 14.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"
      - name: Install Packages
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run Tests
        run: npm run test
